// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6X6-G1q1oWoX-WlUYXNDjdSEIfW3GvQ',
    appId: '1:361031974822:web:395bf07dd321d3cf3ed967',
    messagingSenderId: '361031974822',
    projectId: 'saapp-9ad29',
    authDomain: 'saapp-9ad29.firebaseapp.com',
    databaseURL: 'https://saapp-9ad29-default-rtdb.firebaseio.com',
    storageBucket: 'saapp-9ad29.appspot.com',
    measurementId: 'G-ZC3EQ3CY3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUC7mfZmJRydFi1vWASo_HI_WfUy7rKnU',
    appId: '1:361031974822:android:5c0c4ad4850b75013ed967',
    messagingSenderId: '361031974822',
    projectId: 'saapp-9ad29',
    databaseURL: 'https://saapp-9ad29-default-rtdb.firebaseio.com',
    storageBucket: 'saapp-9ad29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8VW7Q5BaOIhDT4Nc6ALJRLx1qZaLjCdw',
    appId: '1:361031974822:ios:84470c789ba368723ed967',
    messagingSenderId: '361031974822',
    projectId: 'saapp-9ad29',
    databaseURL: 'https://saapp-9ad29-default-rtdb.firebaseio.com',
    storageBucket: 'saapp-9ad29.appspot.com',
    iosClientId: '361031974822-ombdukp2bf1guc74a6fu2dgnkac8qgen.apps.googleusercontent.com',
    iosBundleId: 'com.example.saapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8VW7Q5BaOIhDT4Nc6ALJRLx1qZaLjCdw',
    appId: '1:361031974822:ios:84470c789ba368723ed967',
    messagingSenderId: '361031974822',
    projectId: 'saapp-9ad29',
    databaseURL: 'https://saapp-9ad29-default-rtdb.firebaseio.com',
    storageBucket: 'saapp-9ad29.appspot.com',
    iosClientId: '361031974822-ombdukp2bf1guc74a6fu2dgnkac8qgen.apps.googleusercontent.com',
    iosBundleId: 'com.example.saapp',
  );
}
